name: ac-dpo
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - pip
  - pip:
    - transformers==4.39.3
    - peft==0.10.0
    - datasets
    - trl==0.8.6
    - accelerate==0.27.2
    - wandb
    - ipykernel